### ISSUE TITLE
Keep or remove this app?

### ISSUE THREAD

**Issue by Mackiovello** [StarcounterAppsFreezer/UsageTracker#11]
From https://github.com/Starcounter/CompanyTrack/issues/331

The discussion so far:
**Keep?** It is like a WordPress plugin. You enable it to get one feature in your system. In case of this app, the feature is to add Google Analytics tracking without having to edit HTML of your apps. 

**Delete?** Is extremely general but not very refined. I don't think it's very useful and it has barely been touched the last 2 years

@Mackiovello: Delete
@warpech: Keep

Comment by me:
From your description, it seems like it should be a sample app that shows how to do HTML injections. If that's so, it should be stripped down to its bare minimum to only display that and do so in a clear manner. On the other hand, if the goal is to display how to "enable it to get one feature in your system", I believe that all our apps should display this kind of behavior which would make this app excessive.

**Comment by warpech** [comment]
UsageTracker is actually a prefab, not a sample app, because it was intended for production. We can totally run it in `inside.starcounter.com` for instance. But I agree, it requires maintenance.

**Comment by Mackiovello** [comment]
Then, the question is, how much more useful is it than just pasting the HTML into the code? It feels like it fills a niche purpose.

**Comment by warpech** [comment]
> Then, the question is, how much more useful is it than just pasting the HTML into the code? It feels like it fills a niche purpose.

Into the code of what app?

Imagine I have a system of few apps at `i.s.c`: People, Images, SignIn, UserAdmin, Launcher, Website, WebsiteTheme.

Would you hardcode Google Analytics tracking code in HTML of the WebsiteTheme? 

To use an analogy, it is like hacking a WordPress theme to put Google Analytics there. It is usually the least advised thing to do. Normally you use a plugin: https://digwp.com/2012/06/add-google-analytics-wordpress/

**Comment by warpech** [comment]
I propose to move this app to the freezer.

**Comment by Mackiovello** [comment]
Ah! I get your point, sorry for the misunderstanding.

> I propose to move this app to the freezer.

Yes, I agree

**Comment by warpech** [comment]
Next steps:

- [ ] Make a PR that explains the purpose of this app for future reference.
- [ ] Move this app to https://github.com/StarcounterAppsFreezer. Apps in that organisation do not get updates until we remove them from freezer.

**Comment by warpech** [comment]
All done now
